# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d0ddb0382ac5c784d9b6d26b806dfde5aca266e592a9c68e20be94ec3a0c49f10fc4783a044dd59a90f41ebdf6eccd4067870fb5bdba8cbb79c792cefda655e

test:
  secret_key_base: f3ef06a3159956464bbf34b560cc1376037c630c0c9683533d89352282d1fcae3d89b1cc2c7425b435a8e62ac843e5dd2dc35a0ed1f417a62f0192ad057bd392

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
